name = "zmail-backend"
main = "src/index.ts"

# 打包配置
minify = true # 生产环境压缩代码
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-09-06"

# 启用 D1 数据库
[[d1_databases]]
binding = "DB"
database_name = "email"
database_id = "1b5e4e86-ba4b-4612-b3bf-0c897666f506"  # 需要替换为您的实际数据库 ID

# 配置邮件处理
[triggers]
crons = ["*/10 * * * *"]  # 每10分钟运行一次清理任务

[build]
command = "" # 使用默认打包，不需要自定义构建命令

# 默认开启日志，方便调试
[observability]
enabled = false
head_sampling_rate = 1 # optional. default = 1.
